from typing import Any, Callable, Iterable

def hash_iterable(it: Iterable): ...

class Sentinel:
    def __getnewargs__(self): ...
    def __new__(cls, _name: str): ...
    def __init__(self, name: str) -> None: ...
    def __bool__(self): ...
    def __eq__(self, other: Any): ...

NOT_SET: Sentinel

def deprecated(msg: str, dep_version: str) -> Callable: ...
